pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://alphacephei.com/maven/" }   // Vosk offline ASR + wake word
    }
}

rootProject.name = "OMNIX"
include ':app'
