package com.omnix.agent

// This file is auto-generated by Gradle build system.
// The PORCUPINE_KEY should be set in local.properties or environment variable.
// For now this is a placeholder - actual BuildConfig is generated during build.
object BuildConfig {
    const val APPLICATION_ID = "com.omnix.agent"
    const val BUILD_TYPE = "debug"
    const val DEBUG = true
    const val VERSION_CODE = 1
    const val VERSION_NAME = "1.0.0"

    // Set in local.properties: PORCUPINE_KEY=your_key_here
    // Or via Gradle: buildConfigField("String", "PORCUPINE_KEY", ...)
    const val PORCUPINE_KEY = "" // Set via BuildConfig in actual build
}
